#!/bin/bash

disable_functions="shell_exec,symlink,restore_ini,hopenbasedir,f_open,system,dl,passthru,cat,exec,popen,proc_close,proc_get_status,proc_nice,proc_open,escapeshellcmd,escapeshellarg,show_source,posix_mkfifo,mysql_list_dbs,get_current_user,getmyuid,pconnect,link,symlink,pcntl_exec,leak,apache_child_terminate,posix_kill,posix_setpgid,posix_setsid,posix_setuid,proc_terminate,syslog,fpassthru,socket_select,socket_create,socket_create_listen,socket_create_pair,socket_listen,socket_accept,socket_bind,foreach,socket_strerror,pcntl_fork,pcntl_signal,pcntl_waitpid,pcntl_wexitstatus,pcntl_wifexited,pcntl_wifsignaled,pcntl_wifstopped,pcntl_wstopsig,pcntl_wtermsig,openlog,apache_get_modules,apache_get_version,apache_getenv,apache_note,apache_setenv,virtual,mail,phpmail"

php_versions=$(ls -1 /etc/php | grep -oE '[0-9]+\.[0-9]+')

for php_version in $php_versions; do
    php_ini_path="/etc/php/$php_version/cli/php.ini"
    if [ -f "$php_ini_path" ]; then
        echo "Modifying PHP configuration for PHP $php_version"
        sed -i "s/^\(disable_functions\s*=\s*\).*\$/\1$disable_functions/" "$php_ini_path"
        echo "PHP configuration updated for PHP $php_version"
    else
        echo "PHP $php_version configuration file not found at $php_ini_path"
    fi
done

cloudlinux_php_versions=$(selectorctl --list | grep -oE 'ea-php[0-9]+\.[0-9]+')

for cloudlinux_php_version in $cloudlinux_php_versions; do
    php_ini_path="/opt/alt/php$cloudlinux_php_version/etc/php.ini"
    if [ -f "$php_ini_path" ]; then
        echo "Modifying PHP configuration for CloudLinux PHP $cloudlinux_php_version"
        sed -i "s/^\(disable_functions\s*=\s*\).*\$/\1$disable_functions/" "$php_ini_path"
        echo "PHP configuration updated for CloudLinux PHP $cloudlinux_php_version"
    else
        echo "CloudLinux PHP $cloudlinux_php_version configuration file not found at $php_ini_path"
    fi
done

echo "PHP configuration update completed for all PHP versions"
